config/routes.rb
Html5imageboard::Application.routes.draw do
  resources :boards, :only => [:index, :show, :create] do
    resources :posts
  end

  get "posts/image/:id", to: "posts#image" 

  root :to => "boards#index"

end

app/models/board.rb
class Board < ActiveRecord::Base
  self.per_page = 6
  validates_uniqueness_of :title
  validates_presence_of :title

  has_many :posts
end

app/models/post.rb
class Post < ActiveRecord::Base
  self.per_page = 4
  belongs_to :thread
  validates_presence_of :title, :svg
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  # GET /boards
  # GET /boards.xml
  def index
    @board  = Board.new
    @boards = Board.order(created_at: :desc)
                 .paginate(page: params[:page])
    respond_to do |format|
      format.html # index.html.erb
      #format.xml  { render :xml => @boards }
    end
  end

  # GET /boards/1
  # GET /boards/1.xml
  def show
    @board = Board.find(params[:id])
    @posts = @board.posts.paginate :page => params[:page], :order => 'created_at DESC',:per_page => 4

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @board }
    end
  end

  # GET /boards/1/edit
  def edit
    @board = Board.find(params[:id])
  end

  # POST /boards
  # POST /boards.xml
  def create
    @board = Board.new(params[:board])

    respond_to do |format|
      if @board.save
        format.html { redirect_to(@board, :notice => 'Board was successfully created. Start adding a post...') }
        format.xml  { render :xml => @board, :status => :created, :location => @board }
      else
        @boards = Board.all
        format.html { render :action => "index" }
        format.xml  { render :xml => @board.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /boards/1
  # PUT /boards/1.xml
  def update
    @board = Board.find(params[:id])

    respond_to do |format|
      if @board.update_attributes(params[:board])
        format.html { redirect_to(@board, :notice => 'Image board was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @board.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /boards/1
  # DELETE /boards/1.xml
  def destroy
    @board = Board.find(params[:id])
    @board.destroy

    respond_to do |format|
      format.html { redirect_to(boards_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def create
    params[:post][:svg] = params["drawbox-data"]
    @board = Board.find(params[:board_id])
    @post = @board.posts.create(params[:post])
    if @post.invalid?
      redirect_to board_path(@board), :notice => "can't add post!"
    else
      redirect_to board_path(@board)
    end
  end
  def image
    cache_key = "img-"+params[:id]
    img_data = Rails.cache.read(cache_key)
    unless img_data
      img_data = convert_png(params[:id])
      Rails.cache.write(cache_key, img_data)
    end
    send_data img_data,:type => :png,:disposition => 'inline'
  end
  private
    def convert_png(id)
      require 'RMagick'
      img = Magick::Image.from_blob(Post.find(id).svg)
      img[0].format = "png"
      return img[0].to_blob
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def button(title,options={})
    url = "#" unless options[:url]
    icon = id = "";
    icon = "<span class=\"ui-icon "+options[:icon]+"\"></span>" if options[:icon]
    id = " id=\"#{options[:id]}\"" if options[:id]
    "<a class=\"ib-button ui-state-default ui-corner-all\"#{id} href=\"#{url_for(url)}\" alt=\"#{title}\">#{icon}#{title}</a>".html_safe
  end
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/boards/_form.html.haml
= form_for @board, :html =>{:class => "ib-form"} do |f|
  -if @board.errors.any?
    #error_explanation.ui-state-error.ui-corner-all{:style=>"padding: 0.7em;"}
      %span.ui-icon.ui-icon-alert{:style=>"float: left; margin-right: .3em;"}
      %h2= "#{pluralize(@board.errors.count, "error")} prohibited this board from being saved:"
      %ul
        - @board.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.text_field :title
    = f.submit 'Create thread'

app/views/boards/edit.html.haml
%h1 Editing image_thread

= render 'form'

= link_to 'Show', @image_thread
\|
= link_to 'Back', image_threads_path

app/views/boards/index.html.haml
#new_board
  = button "Create new board",:icon=>"ui-icon-document",:id => "new_board_button" unless @board.errors.any?
  #new_board_form{!@board.errors.any? && :style=>"display:none;"}
    %h2 new board
    %p= render 'form'
%h1 threads
- @boards.each do |board|
  %h2= link_to board.title, board
  %p= "created "+distance_of_time_in_words(Time.now,board.created_at,true) + " ago"
%p= will_paginate @boards

app/views/boards/show.html.haml
%h1= @board.title
%p="created "+distance_of_time_in_words(Time.now,@board.created_at,true)
#posts
  = render :partial => "posts/post", :collection => @posts
  = will_paginate @posts
= button "Add new post", :icon => "ui-icon-plusthick", :id => "new_post_button"
#new_post_form{:style=>"display:none;"}
  %h2 new post
  %p= render 'posts/form'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Html5imageboard
    = stylesheet_link_tag :all
    = javascript_include_tag :defaults
    = csrf_meta_tag
  %body
    %header= link_to image_tag("logo.png",:id=>"logo"),boards_path
    - if notice
      #notice.ui-state-highlight.ui-corner-all
        %span.ui-icon.ui-icon-info
        = notice
    #container= yield

app/views/posts/_form.html.haml
= form_for([@board, @board.posts.build], :html =>{:class => "ib-form"}) do |f|
  .field
    = f.label "Title"
    = f.text_field :title
    %br
    %canvas{:id=>"drawbox",:width=>"500",:height=>"300"}
    = #%button{:id=>"drawbox-clear"} Clear
    %br
    = f.label "Description"
    = f.text_area :description, :rows => "4", :cols => "6"
    %br
    %br
    = f.submit 'Create post'

app/views/posts/_post.html.haml
.post
  %h3= post.title
  %p= image_tag "/posts/image/"+post.id.to_s
  %p= post.description